[package]
name = "sunset-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "UniFFI binding layer between sunset-core and Kotlin/Swift UI."

[dependencies]
sunset-core = { path = "../sunset-core", version = "0.1.0" }
uniffi = { version = "0.32" }

[lib]
crate-type = ["cdylib", "lib"]
